
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports various common sort, input & filter types that are not directly linked to a particular model.
 *
 * 🟢 You can import this file directly.
 */

import type * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.js"
import type * as Prisma from "./internal/prismaNamespace.js"


export type StringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type StringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type IntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type DateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type SortOrderInput = {
  sort: Prisma.SortOrder
  nulls?: Prisma.NullsOrder
}

export type StringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type StringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type IntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type DateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type EnumGradeEnumFilter<$PrismaModel = never> = {
  equals?: $Enums.GradeEnum | Prisma.EnumGradeEnumFieldRefInput<$PrismaModel>
  in?: $Enums.GradeEnum[] | Prisma.ListEnumGradeEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.GradeEnum[] | Prisma.ListEnumGradeEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumGradeEnumFilter<$PrismaModel> | $Enums.GradeEnum
}

export type EnumDifficultyEnumFilter<$PrismaModel = never> = {
  equals?: $Enums.DifficultyEnum | Prisma.EnumDifficultyEnumFieldRefInput<$PrismaModel>
  in?: $Enums.DifficultyEnum[] | Prisma.ListEnumDifficultyEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.DifficultyEnum[] | Prisma.ListEnumDifficultyEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDifficultyEnumFilter<$PrismaModel> | $Enums.DifficultyEnum
}

export type EnumStatusEnumFilter<$PrismaModel = never> = {
  equals?: $Enums.StatusEnum | Prisma.EnumStatusEnumFieldRefInput<$PrismaModel>
  in?: $Enums.StatusEnum[] | Prisma.ListEnumStatusEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.StatusEnum[] | Prisma.ListEnumStatusEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumStatusEnumFilter<$PrismaModel> | $Enums.StatusEnum
}

export type JsonNullableFilter<$PrismaModel = never> =
| Prisma.PatchUndefined<
    Prisma.Either<Required<JsonNullableFilterBase<$PrismaModel>>, Exclude<keyof Required<JsonNullableFilterBase<$PrismaModel>>, 'path'>>,
    Required<JsonNullableFilterBase<$PrismaModel>>
  >
| Prisma.OptionalFlat<Omit<Required<JsonNullableFilterBase<$PrismaModel>>, 'path'>>

export type JsonNullableFilterBase<$PrismaModel = never> = {
  equals?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  path?: string[]
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_contains?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  lt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  lte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  not?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
}

export type EnumGradeEnumWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.GradeEnum | Prisma.EnumGradeEnumFieldRefInput<$PrismaModel>
  in?: $Enums.GradeEnum[] | Prisma.ListEnumGradeEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.GradeEnum[] | Prisma.ListEnumGradeEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumGradeEnumWithAggregatesFilter<$PrismaModel> | $Enums.GradeEnum
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumGradeEnumFilter<$PrismaModel>
  _max?: Prisma.NestedEnumGradeEnumFilter<$PrismaModel>
}

export type EnumDifficultyEnumWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DifficultyEnum | Prisma.EnumDifficultyEnumFieldRefInput<$PrismaModel>
  in?: $Enums.DifficultyEnum[] | Prisma.ListEnumDifficultyEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.DifficultyEnum[] | Prisma.ListEnumDifficultyEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDifficultyEnumWithAggregatesFilter<$PrismaModel> | $Enums.DifficultyEnum
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDifficultyEnumFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDifficultyEnumFilter<$PrismaModel>
}

export type EnumStatusEnumWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.StatusEnum | Prisma.EnumStatusEnumFieldRefInput<$PrismaModel>
  in?: $Enums.StatusEnum[] | Prisma.ListEnumStatusEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.StatusEnum[] | Prisma.ListEnumStatusEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumStatusEnumWithAggregatesFilter<$PrismaModel> | $Enums.StatusEnum
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumStatusEnumFilter<$PrismaModel>
  _max?: Prisma.NestedEnumStatusEnumFilter<$PrismaModel>
}

export type JsonNullableWithAggregatesFilter<$PrismaModel = never> =
| Prisma.PatchUndefined<
    Prisma.Either<Required<JsonNullableWithAggregatesFilterBase<$PrismaModel>>, Exclude<keyof Required<JsonNullableWithAggregatesFilterBase<$PrismaModel>>, 'path'>>,
    Required<JsonNullableWithAggregatesFilterBase<$PrismaModel>>
  >
| Prisma.OptionalFlat<Omit<Required<JsonNullableWithAggregatesFilterBase<$PrismaModel>>, 'path'>>

export type JsonNullableWithAggregatesFilterBase<$PrismaModel = never> = {
  equals?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  path?: string[]
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_contains?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  lt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  lte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  not?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedJsonNullableFilter<$PrismaModel>
  _max?: Prisma.NestedJsonNullableFilter<$PrismaModel>
}

export type EnumMessageRoleEnumFilter<$PrismaModel = never> = {
  equals?: $Enums.MessageRoleEnum | Prisma.EnumMessageRoleEnumFieldRefInput<$PrismaModel>
  in?: $Enums.MessageRoleEnum[] | Prisma.ListEnumMessageRoleEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.MessageRoleEnum[] | Prisma.ListEnumMessageRoleEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMessageRoleEnumFilter<$PrismaModel> | $Enums.MessageRoleEnum
}

export type IntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type EnumMessageRoleEnumWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.MessageRoleEnum | Prisma.EnumMessageRoleEnumFieldRefInput<$PrismaModel>
  in?: $Enums.MessageRoleEnum[] | Prisma.ListEnumMessageRoleEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.MessageRoleEnum[] | Prisma.ListEnumMessageRoleEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMessageRoleEnumWithAggregatesFilter<$PrismaModel> | $Enums.MessageRoleEnum
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumMessageRoleEnumFilter<$PrismaModel>
  _max?: Prisma.NestedEnumMessageRoleEnumFilter<$PrismaModel>
}

export type IntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _max?: Prisma.NestedIntNullableFilter<$PrismaModel>
}

export type EnumTokenEnumFilter<$PrismaModel = never> = {
  equals?: $Enums.TokenEnum | Prisma.EnumTokenEnumFieldRefInput<$PrismaModel>
  in?: $Enums.TokenEnum[] | Prisma.ListEnumTokenEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.TokenEnum[] | Prisma.ListEnumTokenEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTokenEnumFilter<$PrismaModel> | $Enums.TokenEnum
}

export type EnumTokenEnumWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TokenEnum | Prisma.EnumTokenEnumFieldRefInput<$PrismaModel>
  in?: $Enums.TokenEnum[] | Prisma.ListEnumTokenEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.TokenEnum[] | Prisma.ListEnumTokenEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTokenEnumWithAggregatesFilter<$PrismaModel> | $Enums.TokenEnum
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumTokenEnumFilter<$PrismaModel>
  _max?: Prisma.NestedEnumTokenEnumFilter<$PrismaModel>
}

export type EnumUserRoleEnumFilter<$PrismaModel = never> = {
  equals?: $Enums.UserRoleEnum | Prisma.EnumUserRoleEnumFieldRefInput<$PrismaModel>
  in?: $Enums.UserRoleEnum[] | Prisma.ListEnumUserRoleEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserRoleEnum[] | Prisma.ListEnumUserRoleEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumUserRoleEnumFilter<$PrismaModel> | $Enums.UserRoleEnum
}

export type BoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type EnumAuthMethodEnumFilter<$PrismaModel = never> = {
  equals?: $Enums.AuthMethodEnum | Prisma.EnumAuthMethodEnumFieldRefInput<$PrismaModel>
  in?: $Enums.AuthMethodEnum[] | Prisma.ListEnumAuthMethodEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.AuthMethodEnum[] | Prisma.ListEnumAuthMethodEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumAuthMethodEnumFilter<$PrismaModel> | $Enums.AuthMethodEnum
}

export type EnumUserRoleEnumWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.UserRoleEnum | Prisma.EnumUserRoleEnumFieldRefInput<$PrismaModel>
  in?: $Enums.UserRoleEnum[] | Prisma.ListEnumUserRoleEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserRoleEnum[] | Prisma.ListEnumUserRoleEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumUserRoleEnumWithAggregatesFilter<$PrismaModel> | $Enums.UserRoleEnum
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumUserRoleEnumFilter<$PrismaModel>
  _max?: Prisma.NestedEnumUserRoleEnumFilter<$PrismaModel>
}

export type BoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type EnumAuthMethodEnumWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.AuthMethodEnum | Prisma.EnumAuthMethodEnumFieldRefInput<$PrismaModel>
  in?: $Enums.AuthMethodEnum[] | Prisma.ListEnumAuthMethodEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.AuthMethodEnum[] | Prisma.ListEnumAuthMethodEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumAuthMethodEnumWithAggregatesFilter<$PrismaModel> | $Enums.AuthMethodEnum
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumAuthMethodEnumFilter<$PrismaModel>
  _max?: Prisma.NestedEnumAuthMethodEnumFilter<$PrismaModel>
}

export type NestedStringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type NestedStringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type NestedIntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type NestedDateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type NestedStringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type NestedStringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type NestedIntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type NestedIntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type NestedFloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number
}

export type NestedDateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type NestedEnumGradeEnumFilter<$PrismaModel = never> = {
  equals?: $Enums.GradeEnum | Prisma.EnumGradeEnumFieldRefInput<$PrismaModel>
  in?: $Enums.GradeEnum[] | Prisma.ListEnumGradeEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.GradeEnum[] | Prisma.ListEnumGradeEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumGradeEnumFilter<$PrismaModel> | $Enums.GradeEnum
}

export type NestedEnumDifficultyEnumFilter<$PrismaModel = never> = {
  equals?: $Enums.DifficultyEnum | Prisma.EnumDifficultyEnumFieldRefInput<$PrismaModel>
  in?: $Enums.DifficultyEnum[] | Prisma.ListEnumDifficultyEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.DifficultyEnum[] | Prisma.ListEnumDifficultyEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDifficultyEnumFilter<$PrismaModel> | $Enums.DifficultyEnum
}

export type NestedEnumStatusEnumFilter<$PrismaModel = never> = {
  equals?: $Enums.StatusEnum | Prisma.EnumStatusEnumFieldRefInput<$PrismaModel>
  in?: $Enums.StatusEnum[] | Prisma.ListEnumStatusEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.StatusEnum[] | Prisma.ListEnumStatusEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumStatusEnumFilter<$PrismaModel> | $Enums.StatusEnum
}

export type NestedEnumGradeEnumWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.GradeEnum | Prisma.EnumGradeEnumFieldRefInput<$PrismaModel>
  in?: $Enums.GradeEnum[] | Prisma.ListEnumGradeEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.GradeEnum[] | Prisma.ListEnumGradeEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumGradeEnumWithAggregatesFilter<$PrismaModel> | $Enums.GradeEnum
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumGradeEnumFilter<$PrismaModel>
  _max?: Prisma.NestedEnumGradeEnumFilter<$PrismaModel>
}

export type NestedEnumDifficultyEnumWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DifficultyEnum | Prisma.EnumDifficultyEnumFieldRefInput<$PrismaModel>
  in?: $Enums.DifficultyEnum[] | Prisma.ListEnumDifficultyEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.DifficultyEnum[] | Prisma.ListEnumDifficultyEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumDifficultyEnumWithAggregatesFilter<$PrismaModel> | $Enums.DifficultyEnum
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDifficultyEnumFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDifficultyEnumFilter<$PrismaModel>
}

export type NestedEnumStatusEnumWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.StatusEnum | Prisma.EnumStatusEnumFieldRefInput<$PrismaModel>
  in?: $Enums.StatusEnum[] | Prisma.ListEnumStatusEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.StatusEnum[] | Prisma.ListEnumStatusEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumStatusEnumWithAggregatesFilter<$PrismaModel> | $Enums.StatusEnum
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumStatusEnumFilter<$PrismaModel>
  _max?: Prisma.NestedEnumStatusEnumFilter<$PrismaModel>
}

export type NestedJsonNullableFilter<$PrismaModel = never> =
| Prisma.PatchUndefined<
    Prisma.Either<Required<NestedJsonNullableFilterBase<$PrismaModel>>, Exclude<keyof Required<NestedJsonNullableFilterBase<$PrismaModel>>, 'path'>>,
    Required<NestedJsonNullableFilterBase<$PrismaModel>>
  >
| Prisma.OptionalFlat<Omit<Required<NestedJsonNullableFilterBase<$PrismaModel>>, 'path'>>

export type NestedJsonNullableFilterBase<$PrismaModel = never> = {
  equals?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  path?: string[]
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_contains?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  lt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  lte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  not?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
}

export type NestedEnumMessageRoleEnumFilter<$PrismaModel = never> = {
  equals?: $Enums.MessageRoleEnum | Prisma.EnumMessageRoleEnumFieldRefInput<$PrismaModel>
  in?: $Enums.MessageRoleEnum[] | Prisma.ListEnumMessageRoleEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.MessageRoleEnum[] | Prisma.ListEnumMessageRoleEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMessageRoleEnumFilter<$PrismaModel> | $Enums.MessageRoleEnum
}

export type NestedEnumMessageRoleEnumWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.MessageRoleEnum | Prisma.EnumMessageRoleEnumFieldRefInput<$PrismaModel>
  in?: $Enums.MessageRoleEnum[] | Prisma.ListEnumMessageRoleEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.MessageRoleEnum[] | Prisma.ListEnumMessageRoleEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMessageRoleEnumWithAggregatesFilter<$PrismaModel> | $Enums.MessageRoleEnum
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumMessageRoleEnumFilter<$PrismaModel>
  _max?: Prisma.NestedEnumMessageRoleEnumFilter<$PrismaModel>
}

export type NestedIntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _max?: Prisma.NestedIntNullableFilter<$PrismaModel>
}

export type NestedFloatNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatNullableFilter<$PrismaModel> | number | null
}

export type NestedEnumTokenEnumFilter<$PrismaModel = never> = {
  equals?: $Enums.TokenEnum | Prisma.EnumTokenEnumFieldRefInput<$PrismaModel>
  in?: $Enums.TokenEnum[] | Prisma.ListEnumTokenEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.TokenEnum[] | Prisma.ListEnumTokenEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTokenEnumFilter<$PrismaModel> | $Enums.TokenEnum
}

export type NestedEnumTokenEnumWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TokenEnum | Prisma.EnumTokenEnumFieldRefInput<$PrismaModel>
  in?: $Enums.TokenEnum[] | Prisma.ListEnumTokenEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.TokenEnum[] | Prisma.ListEnumTokenEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTokenEnumWithAggregatesFilter<$PrismaModel> | $Enums.TokenEnum
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumTokenEnumFilter<$PrismaModel>
  _max?: Prisma.NestedEnumTokenEnumFilter<$PrismaModel>
}

export type NestedEnumUserRoleEnumFilter<$PrismaModel = never> = {
  equals?: $Enums.UserRoleEnum | Prisma.EnumUserRoleEnumFieldRefInput<$PrismaModel>
  in?: $Enums.UserRoleEnum[] | Prisma.ListEnumUserRoleEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserRoleEnum[] | Prisma.ListEnumUserRoleEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumUserRoleEnumFilter<$PrismaModel> | $Enums.UserRoleEnum
}

export type NestedBoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type NestedEnumAuthMethodEnumFilter<$PrismaModel = never> = {
  equals?: $Enums.AuthMethodEnum | Prisma.EnumAuthMethodEnumFieldRefInput<$PrismaModel>
  in?: $Enums.AuthMethodEnum[] | Prisma.ListEnumAuthMethodEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.AuthMethodEnum[] | Prisma.ListEnumAuthMethodEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumAuthMethodEnumFilter<$PrismaModel> | $Enums.AuthMethodEnum
}

export type NestedEnumUserRoleEnumWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.UserRoleEnum | Prisma.EnumUserRoleEnumFieldRefInput<$PrismaModel>
  in?: $Enums.UserRoleEnum[] | Prisma.ListEnumUserRoleEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserRoleEnum[] | Prisma.ListEnumUserRoleEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumUserRoleEnumWithAggregatesFilter<$PrismaModel> | $Enums.UserRoleEnum
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumUserRoleEnumFilter<$PrismaModel>
  _max?: Prisma.NestedEnumUserRoleEnumFilter<$PrismaModel>
}

export type NestedBoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type NestedEnumAuthMethodEnumWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.AuthMethodEnum | Prisma.EnumAuthMethodEnumFieldRefInput<$PrismaModel>
  in?: $Enums.AuthMethodEnum[] | Prisma.ListEnumAuthMethodEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.AuthMethodEnum[] | Prisma.ListEnumAuthMethodEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumAuthMethodEnumWithAggregatesFilter<$PrismaModel> | $Enums.AuthMethodEnum
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumAuthMethodEnumFilter<$PrismaModel>
  _max?: Prisma.NestedEnumAuthMethodEnumFilter<$PrismaModel>
}


