
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const UserRoleEnum = {
  REGULAR: 'REGULAR',
  ADMIN: 'ADMIN'
} as const

export type UserRoleEnum = (typeof UserRoleEnum)[keyof typeof UserRoleEnum]


export const GradeEnum = {
  TRAINEE: 'TRAINEE',
  JUNIOR: 'JUNIOR',
  MIDDLE: 'MIDDLE',
  SENIOR: 'SENIOR'
} as const

export type GradeEnum = (typeof GradeEnum)[keyof typeof GradeEnum]


export const DifficultyEnum = {
  PUPPY: 'PUPPY',
  STRICT: 'STRICT',
  HARD: 'HARD'
} as const

export type DifficultyEnum = (typeof DifficultyEnum)[keyof typeof DifficultyEnum]


export const AuthMethodEnum = {
  CREDENTIALS: 'CREDENTIALS',
  YANDEX: 'YANDEX'
} as const

export type AuthMethodEnum = (typeof AuthMethodEnum)[keyof typeof AuthMethodEnum]


export const TokenEnum = {
  VERIFICATION: 'VERIFICATION',
  PASSWORD_RESET: 'PASSWORD_RESET'
} as const

export type TokenEnum = (typeof TokenEnum)[keyof typeof TokenEnum]


export const StatusEnum = {
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED'
} as const

export type StatusEnum = (typeof StatusEnum)[keyof typeof StatusEnum]


export const MessageRoleEnum = {
  user: 'user',
  assistant: 'assistant'
} as const

export type MessageRoleEnum = (typeof MessageRoleEnum)[keyof typeof MessageRoleEnum]


export const EmotionsEnum = {
  COOL: 'COOL',
  NEUTRAL: 'NEUTRAL',
  SMIRK: 'SMIRK',
  FACEPALM: 'FACEPALM',
  ANGRY: 'ANGRY',
  FURIOUS: 'FURIOUS'
} as const

export type EmotionsEnum = (typeof EmotionsEnum)[keyof typeof EmotionsEnum]
