
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const UserRole = {
  REGULAR: 'REGULAR',
  ADMIN: 'ADMIN'
} as const

export type UserRole = (typeof UserRole)[keyof typeof UserRole]


export const Grade = {
  Trainee: 'Trainee',
  Junior: 'Junior',
  Middle: 'Middle',
  Senior: 'Senior'
} as const

export type Grade = (typeof Grade)[keyof typeof Grade]


export const AuthMethod = {
  CREDENTIALS: 'CREDENTIALS',
  YANDEX: 'YANDEX'
} as const

export type AuthMethod = (typeof AuthMethod)[keyof typeof AuthMethod]


export const TokenType = {
  VERIFICATION: 'VERIFICATION',
  PASSWORD_RESET: 'PASSWORD_RESET'
} as const

export type TokenType = (typeof TokenType)[keyof typeof TokenType]


export const StatusType = {
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED'
} as const

export type StatusType = (typeof StatusType)[keyof typeof StatusType]


export const RoleType = {
  USER: 'USER',
  AI: 'AI'
} as const

export type RoleType = (typeof RoleType)[keyof typeof RoleType]
