
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Interview` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Interview
 * 
 */
export type InterviewModel = runtime.Types.Result.DefaultSelection<Prisma.$InterviewPayload>

export type AggregateInterview = {
  _count: InterviewCountAggregateOutputType | null
  _avg: InterviewAvgAggregateOutputType | null
  _sum: InterviewSumAggregateOutputType | null
  _min: InterviewMinAggregateOutputType | null
  _max: InterviewMaxAggregateOutputType | null
}

export type InterviewAvgAggregateOutputType = {
  hp: number | null
}

export type InterviewSumAggregateOutputType = {
  hp: number | null
}

export type InterviewMinAggregateOutputType = {
  id: string | null
  userId: string | null
  topic: string | null
  grade: $Enums.GradeEnum | null
  difficulty: $Enums.DifficultyEnum | null
  status: $Enums.StatusEnum | null
  hp: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type InterviewMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  topic: string | null
  grade: $Enums.GradeEnum | null
  difficulty: $Enums.DifficultyEnum | null
  status: $Enums.StatusEnum | null
  hp: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type InterviewCountAggregateOutputType = {
  id: number
  userId: number
  topic: number
  grade: number
  difficulty: number
  status: number
  hp: number
  feedback: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type InterviewAvgAggregateInputType = {
  hp?: true
}

export type InterviewSumAggregateInputType = {
  hp?: true
}

export type InterviewMinAggregateInputType = {
  id?: true
  userId?: true
  topic?: true
  grade?: true
  difficulty?: true
  status?: true
  hp?: true
  createdAt?: true
  updatedAt?: true
}

export type InterviewMaxAggregateInputType = {
  id?: true
  userId?: true
  topic?: true
  grade?: true
  difficulty?: true
  status?: true
  hp?: true
  createdAt?: true
  updatedAt?: true
}

export type InterviewCountAggregateInputType = {
  id?: true
  userId?: true
  topic?: true
  grade?: true
  difficulty?: true
  status?: true
  hp?: true
  feedback?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type InterviewAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Interview to aggregate.
   */
  where?: Prisma.InterviewWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Interviews to fetch.
   */
  orderBy?: Prisma.InterviewOrderByWithRelationInput | Prisma.InterviewOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.InterviewWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Interviews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Interviews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Interviews
  **/
  _count?: true | InterviewCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: InterviewAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: InterviewSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: InterviewMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: InterviewMaxAggregateInputType
}

export type GetInterviewAggregateType<T extends InterviewAggregateArgs> = {
      [P in keyof T & keyof AggregateInterview]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateInterview[P]>
    : Prisma.GetScalarType<T[P], AggregateInterview[P]>
}




export type InterviewGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InterviewWhereInput
  orderBy?: Prisma.InterviewOrderByWithAggregationInput | Prisma.InterviewOrderByWithAggregationInput[]
  by: Prisma.InterviewScalarFieldEnum[] | Prisma.InterviewScalarFieldEnum
  having?: Prisma.InterviewScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: InterviewCountAggregateInputType | true
  _avg?: InterviewAvgAggregateInputType
  _sum?: InterviewSumAggregateInputType
  _min?: InterviewMinAggregateInputType
  _max?: InterviewMaxAggregateInputType
}

export type InterviewGroupByOutputType = {
  id: string
  userId: string
  topic: string
  grade: $Enums.GradeEnum
  difficulty: $Enums.DifficultyEnum
  status: $Enums.StatusEnum
  hp: number
  feedback:PrismaJson.IInterviewFeedback | null
  createdAt: Date
  updatedAt: Date
  _count: InterviewCountAggregateOutputType | null
  _avg: InterviewAvgAggregateOutputType | null
  _sum: InterviewSumAggregateOutputType | null
  _min: InterviewMinAggregateOutputType | null
  _max: InterviewMaxAggregateOutputType | null
}

export type GetInterviewGroupByPayload<T extends InterviewGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<InterviewGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof InterviewGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], InterviewGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], InterviewGroupByOutputType[P]>
      }
    >
  >



export type InterviewWhereInput = {
  AND?: Prisma.InterviewWhereInput | Prisma.InterviewWhereInput[]
  OR?: Prisma.InterviewWhereInput[]
  NOT?: Prisma.InterviewWhereInput | Prisma.InterviewWhereInput[]
  id?: Prisma.StringFilter<"Interview"> | string
  userId?: Prisma.StringFilter<"Interview"> | string
  topic?: Prisma.StringFilter<"Interview"> | string
  grade?: Prisma.EnumGradeEnumFilter<"Interview"> | $Enums.GradeEnum
  difficulty?: Prisma.EnumDifficultyEnumFilter<"Interview"> | $Enums.DifficultyEnum
  status?: Prisma.EnumStatusEnumFilter<"Interview"> | $Enums.StatusEnum
  hp?: Prisma.IntFilter<"Interview"> | number
  feedback?: Prisma.JsonNullableFilter<"Interview">
  createdAt?: Prisma.DateTimeFilter<"Interview"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Interview"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  messages?: Prisma.MessageListRelationFilter
}

export type InterviewOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  topic?: Prisma.SortOrder
  grade?: Prisma.SortOrder
  difficulty?: Prisma.SortOrder
  status?: Prisma.SortOrder
  hp?: Prisma.SortOrder
  feedback?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  messages?: Prisma.MessageOrderByRelationAggregateInput
}

export type InterviewWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.InterviewWhereInput | Prisma.InterviewWhereInput[]
  OR?: Prisma.InterviewWhereInput[]
  NOT?: Prisma.InterviewWhereInput | Prisma.InterviewWhereInput[]
  userId?: Prisma.StringFilter<"Interview"> | string
  topic?: Prisma.StringFilter<"Interview"> | string
  grade?: Prisma.EnumGradeEnumFilter<"Interview"> | $Enums.GradeEnum
  difficulty?: Prisma.EnumDifficultyEnumFilter<"Interview"> | $Enums.DifficultyEnum
  status?: Prisma.EnumStatusEnumFilter<"Interview"> | $Enums.StatusEnum
  hp?: Prisma.IntFilter<"Interview"> | number
  feedback?: Prisma.JsonNullableFilter<"Interview">
  createdAt?: Prisma.DateTimeFilter<"Interview"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Interview"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  messages?: Prisma.MessageListRelationFilter
}, "id">

export type InterviewOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  topic?: Prisma.SortOrder
  grade?: Prisma.SortOrder
  difficulty?: Prisma.SortOrder
  status?: Prisma.SortOrder
  hp?: Prisma.SortOrder
  feedback?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.InterviewCountOrderByAggregateInput
  _avg?: Prisma.InterviewAvgOrderByAggregateInput
  _max?: Prisma.InterviewMaxOrderByAggregateInput
  _min?: Prisma.InterviewMinOrderByAggregateInput
  _sum?: Prisma.InterviewSumOrderByAggregateInput
}

export type InterviewScalarWhereWithAggregatesInput = {
  AND?: Prisma.InterviewScalarWhereWithAggregatesInput | Prisma.InterviewScalarWhereWithAggregatesInput[]
  OR?: Prisma.InterviewScalarWhereWithAggregatesInput[]
  NOT?: Prisma.InterviewScalarWhereWithAggregatesInput | Prisma.InterviewScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Interview"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Interview"> | string
  topic?: Prisma.StringWithAggregatesFilter<"Interview"> | string
  grade?: Prisma.EnumGradeEnumWithAggregatesFilter<"Interview"> | $Enums.GradeEnum
  difficulty?: Prisma.EnumDifficultyEnumWithAggregatesFilter<"Interview"> | $Enums.DifficultyEnum
  status?: Prisma.EnumStatusEnumWithAggregatesFilter<"Interview"> | $Enums.StatusEnum
  hp?: Prisma.IntWithAggregatesFilter<"Interview"> | number
  feedback?: Prisma.JsonNullableWithAggregatesFilter<"Interview">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Interview"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Interview"> | Date | string
}

export type InterviewCreateInput = {
  id?: string
  topic: string
  grade: $Enums.GradeEnum
  difficulty: $Enums.DifficultyEnum
  status?: $Enums.StatusEnum
  hp?: number
  feedback?:PrismaJson.IInterviewFeedback | Prisma.NullableJsonNullValueInput
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutInterviewsInput
  messages?: Prisma.MessageCreateNestedManyWithoutInterviewInput
}

export type InterviewUncheckedCreateInput = {
  id?: string
  userId: string
  topic: string
  grade: $Enums.GradeEnum
  difficulty: $Enums.DifficultyEnum
  status?: $Enums.StatusEnum
  hp?: number
  feedback?:PrismaJson.IInterviewFeedback | Prisma.NullableJsonNullValueInput
  createdAt?: Date | string
  updatedAt?: Date | string
  messages?: Prisma.MessageUncheckedCreateNestedManyWithoutInterviewInput
}

export type InterviewUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.EnumGradeEnumFieldUpdateOperationsInput | $Enums.GradeEnum
  difficulty?: Prisma.EnumDifficultyEnumFieldUpdateOperationsInput | $Enums.DifficultyEnum
  status?: Prisma.EnumStatusEnumFieldUpdateOperationsInput | $Enums.StatusEnum
  hp?: Prisma.IntFieldUpdateOperationsInput | number
  feedback?:PrismaJson.IInterviewFeedback | Prisma.NullableJsonNullValueInput
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutInterviewsNestedInput
  messages?: Prisma.MessageUpdateManyWithoutInterviewNestedInput
}

export type InterviewUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.EnumGradeEnumFieldUpdateOperationsInput | $Enums.GradeEnum
  difficulty?: Prisma.EnumDifficultyEnumFieldUpdateOperationsInput | $Enums.DifficultyEnum
  status?: Prisma.EnumStatusEnumFieldUpdateOperationsInput | $Enums.StatusEnum
  hp?: Prisma.IntFieldUpdateOperationsInput | number
  feedback?:PrismaJson.IInterviewFeedback | Prisma.NullableJsonNullValueInput
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  messages?: Prisma.MessageUncheckedUpdateManyWithoutInterviewNestedInput
}

export type InterviewCreateManyInput = {
  id?: string
  userId: string
  topic: string
  grade: $Enums.GradeEnum
  difficulty: $Enums.DifficultyEnum
  status?: $Enums.StatusEnum
  hp?: number
  feedback?:PrismaJson.IInterviewFeedback | Prisma.NullableJsonNullValueInput
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type InterviewUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.EnumGradeEnumFieldUpdateOperationsInput | $Enums.GradeEnum
  difficulty?: Prisma.EnumDifficultyEnumFieldUpdateOperationsInput | $Enums.DifficultyEnum
  status?: Prisma.EnumStatusEnumFieldUpdateOperationsInput | $Enums.StatusEnum
  hp?: Prisma.IntFieldUpdateOperationsInput | number
  feedback?:PrismaJson.IInterviewFeedback | Prisma.NullableJsonNullValueInput
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InterviewUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.EnumGradeEnumFieldUpdateOperationsInput | $Enums.GradeEnum
  difficulty?: Prisma.EnumDifficultyEnumFieldUpdateOperationsInput | $Enums.DifficultyEnum
  status?: Prisma.EnumStatusEnumFieldUpdateOperationsInput | $Enums.StatusEnum
  hp?: Prisma.IntFieldUpdateOperationsInput | number
  feedback?:PrismaJson.IInterviewFeedback | Prisma.NullableJsonNullValueInput
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InterviewCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  topic?: Prisma.SortOrder
  grade?: Prisma.SortOrder
  difficulty?: Prisma.SortOrder
  status?: Prisma.SortOrder
  hp?: Prisma.SortOrder
  feedback?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type InterviewAvgOrderByAggregateInput = {
  hp?: Prisma.SortOrder
}

export type InterviewMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  topic?: Prisma.SortOrder
  grade?: Prisma.SortOrder
  difficulty?: Prisma.SortOrder
  status?: Prisma.SortOrder
  hp?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type InterviewMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  topic?: Prisma.SortOrder
  grade?: Prisma.SortOrder
  difficulty?: Prisma.SortOrder
  status?: Prisma.SortOrder
  hp?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type InterviewSumOrderByAggregateInput = {
  hp?: Prisma.SortOrder
}

export type InterviewScalarRelationFilter = {
  is?: Prisma.InterviewWhereInput
  isNot?: Prisma.InterviewWhereInput
}

export type InterviewListRelationFilter = {
  every?: Prisma.InterviewWhereInput
  some?: Prisma.InterviewWhereInput
  none?: Prisma.InterviewWhereInput
}

export type InterviewOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EnumGradeEnumFieldUpdateOperationsInput = {
  set?: $Enums.GradeEnum
}

export type EnumDifficultyEnumFieldUpdateOperationsInput = {
  set?: $Enums.DifficultyEnum
}

export type EnumStatusEnumFieldUpdateOperationsInput = {
  set?: $Enums.StatusEnum
}

export type InterviewCreateNestedOneWithoutMessagesInput = {
  create?: Prisma.XOR<Prisma.InterviewCreateWithoutMessagesInput, Prisma.InterviewUncheckedCreateWithoutMessagesInput>
  connectOrCreate?: Prisma.InterviewCreateOrConnectWithoutMessagesInput
  connect?: Prisma.InterviewWhereUniqueInput
}

export type InterviewUpdateOneRequiredWithoutMessagesNestedInput = {
  create?: Prisma.XOR<Prisma.InterviewCreateWithoutMessagesInput, Prisma.InterviewUncheckedCreateWithoutMessagesInput>
  connectOrCreate?: Prisma.InterviewCreateOrConnectWithoutMessagesInput
  upsert?: Prisma.InterviewUpsertWithoutMessagesInput
  connect?: Prisma.InterviewWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.InterviewUpdateToOneWithWhereWithoutMessagesInput, Prisma.InterviewUpdateWithoutMessagesInput>, Prisma.InterviewUncheckedUpdateWithoutMessagesInput>
}

export type InterviewCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.InterviewCreateWithoutUserInput, Prisma.InterviewUncheckedCreateWithoutUserInput> | Prisma.InterviewCreateWithoutUserInput[] | Prisma.InterviewUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.InterviewCreateOrConnectWithoutUserInput | Prisma.InterviewCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.InterviewCreateManyUserInputEnvelope
  connect?: Prisma.InterviewWhereUniqueInput | Prisma.InterviewWhereUniqueInput[]
}

export type InterviewUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.InterviewCreateWithoutUserInput, Prisma.InterviewUncheckedCreateWithoutUserInput> | Prisma.InterviewCreateWithoutUserInput[] | Prisma.InterviewUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.InterviewCreateOrConnectWithoutUserInput | Prisma.InterviewCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.InterviewCreateManyUserInputEnvelope
  connect?: Prisma.InterviewWhereUniqueInput | Prisma.InterviewWhereUniqueInput[]
}

export type InterviewUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.InterviewCreateWithoutUserInput, Prisma.InterviewUncheckedCreateWithoutUserInput> | Prisma.InterviewCreateWithoutUserInput[] | Prisma.InterviewUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.InterviewCreateOrConnectWithoutUserInput | Prisma.InterviewCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.InterviewUpsertWithWhereUniqueWithoutUserInput | Prisma.InterviewUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.InterviewCreateManyUserInputEnvelope
  set?: Prisma.InterviewWhereUniqueInput | Prisma.InterviewWhereUniqueInput[]
  disconnect?: Prisma.InterviewWhereUniqueInput | Prisma.InterviewWhereUniqueInput[]
  delete?: Prisma.InterviewWhereUniqueInput | Prisma.InterviewWhereUniqueInput[]
  connect?: Prisma.InterviewWhereUniqueInput | Prisma.InterviewWhereUniqueInput[]
  update?: Prisma.InterviewUpdateWithWhereUniqueWithoutUserInput | Prisma.InterviewUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.InterviewUpdateManyWithWhereWithoutUserInput | Prisma.InterviewUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.InterviewScalarWhereInput | Prisma.InterviewScalarWhereInput[]
}

export type InterviewUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.InterviewCreateWithoutUserInput, Prisma.InterviewUncheckedCreateWithoutUserInput> | Prisma.InterviewCreateWithoutUserInput[] | Prisma.InterviewUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.InterviewCreateOrConnectWithoutUserInput | Prisma.InterviewCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.InterviewUpsertWithWhereUniqueWithoutUserInput | Prisma.InterviewUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.InterviewCreateManyUserInputEnvelope
  set?: Prisma.InterviewWhereUniqueInput | Prisma.InterviewWhereUniqueInput[]
  disconnect?: Prisma.InterviewWhereUniqueInput | Prisma.InterviewWhereUniqueInput[]
  delete?: Prisma.InterviewWhereUniqueInput | Prisma.InterviewWhereUniqueInput[]
  connect?: Prisma.InterviewWhereUniqueInput | Prisma.InterviewWhereUniqueInput[]
  update?: Prisma.InterviewUpdateWithWhereUniqueWithoutUserInput | Prisma.InterviewUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.InterviewUpdateManyWithWhereWithoutUserInput | Prisma.InterviewUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.InterviewScalarWhereInput | Prisma.InterviewScalarWhereInput[]
}

export type InterviewCreateWithoutMessagesInput = {
  id?: string
  topic: string
  grade: $Enums.GradeEnum
  difficulty: $Enums.DifficultyEnum
  status?: $Enums.StatusEnum
  hp?: number
  feedback?:PrismaJson.IInterviewFeedback | Prisma.NullableJsonNullValueInput
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutInterviewsInput
}

export type InterviewUncheckedCreateWithoutMessagesInput = {
  id?: string
  userId: string
  topic: string
  grade: $Enums.GradeEnum
  difficulty: $Enums.DifficultyEnum
  status?: $Enums.StatusEnum
  hp?: number
  feedback?:PrismaJson.IInterviewFeedback | Prisma.NullableJsonNullValueInput
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type InterviewCreateOrConnectWithoutMessagesInput = {
  where: Prisma.InterviewWhereUniqueInput
  create: Prisma.XOR<Prisma.InterviewCreateWithoutMessagesInput, Prisma.InterviewUncheckedCreateWithoutMessagesInput>
}

export type InterviewUpsertWithoutMessagesInput = {
  update: Prisma.XOR<Prisma.InterviewUpdateWithoutMessagesInput, Prisma.InterviewUncheckedUpdateWithoutMessagesInput>
  create: Prisma.XOR<Prisma.InterviewCreateWithoutMessagesInput, Prisma.InterviewUncheckedCreateWithoutMessagesInput>
  where?: Prisma.InterviewWhereInput
}

export type InterviewUpdateToOneWithWhereWithoutMessagesInput = {
  where?: Prisma.InterviewWhereInput
  data: Prisma.XOR<Prisma.InterviewUpdateWithoutMessagesInput, Prisma.InterviewUncheckedUpdateWithoutMessagesInput>
}

export type InterviewUpdateWithoutMessagesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.EnumGradeEnumFieldUpdateOperationsInput | $Enums.GradeEnum
  difficulty?: Prisma.EnumDifficultyEnumFieldUpdateOperationsInput | $Enums.DifficultyEnum
  status?: Prisma.EnumStatusEnumFieldUpdateOperationsInput | $Enums.StatusEnum
  hp?: Prisma.IntFieldUpdateOperationsInput | number
  feedback?:PrismaJson.IInterviewFeedback | Prisma.NullableJsonNullValueInput
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutInterviewsNestedInput
}

export type InterviewUncheckedUpdateWithoutMessagesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.EnumGradeEnumFieldUpdateOperationsInput | $Enums.GradeEnum
  difficulty?: Prisma.EnumDifficultyEnumFieldUpdateOperationsInput | $Enums.DifficultyEnum
  status?: Prisma.EnumStatusEnumFieldUpdateOperationsInput | $Enums.StatusEnum
  hp?: Prisma.IntFieldUpdateOperationsInput | number
  feedback?:PrismaJson.IInterviewFeedback | Prisma.NullableJsonNullValueInput
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InterviewCreateWithoutUserInput = {
  id?: string
  topic: string
  grade: $Enums.GradeEnum
  difficulty: $Enums.DifficultyEnum
  status?: $Enums.StatusEnum
  hp?: number
  feedback?:PrismaJson.IInterviewFeedback | Prisma.NullableJsonNullValueInput
  createdAt?: Date | string
  updatedAt?: Date | string
  messages?: Prisma.MessageCreateNestedManyWithoutInterviewInput
}

export type InterviewUncheckedCreateWithoutUserInput = {
  id?: string
  topic: string
  grade: $Enums.GradeEnum
  difficulty: $Enums.DifficultyEnum
  status?: $Enums.StatusEnum
  hp?: number
  feedback?:PrismaJson.IInterviewFeedback | Prisma.NullableJsonNullValueInput
  createdAt?: Date | string
  updatedAt?: Date | string
  messages?: Prisma.MessageUncheckedCreateNestedManyWithoutInterviewInput
}

export type InterviewCreateOrConnectWithoutUserInput = {
  where: Prisma.InterviewWhereUniqueInput
  create: Prisma.XOR<Prisma.InterviewCreateWithoutUserInput, Prisma.InterviewUncheckedCreateWithoutUserInput>
}

export type InterviewCreateManyUserInputEnvelope = {
  data: Prisma.InterviewCreateManyUserInput | Prisma.InterviewCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type InterviewUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.InterviewWhereUniqueInput
  update: Prisma.XOR<Prisma.InterviewUpdateWithoutUserInput, Prisma.InterviewUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.InterviewCreateWithoutUserInput, Prisma.InterviewUncheckedCreateWithoutUserInput>
}

export type InterviewUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.InterviewWhereUniqueInput
  data: Prisma.XOR<Prisma.InterviewUpdateWithoutUserInput, Prisma.InterviewUncheckedUpdateWithoutUserInput>
}

export type InterviewUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.InterviewScalarWhereInput
  data: Prisma.XOR<Prisma.InterviewUpdateManyMutationInput, Prisma.InterviewUncheckedUpdateManyWithoutUserInput>
}

export type InterviewScalarWhereInput = {
  AND?: Prisma.InterviewScalarWhereInput | Prisma.InterviewScalarWhereInput[]
  OR?: Prisma.InterviewScalarWhereInput[]
  NOT?: Prisma.InterviewScalarWhereInput | Prisma.InterviewScalarWhereInput[]
  id?: Prisma.StringFilter<"Interview"> | string
  userId?: Prisma.StringFilter<"Interview"> | string
  topic?: Prisma.StringFilter<"Interview"> | string
  grade?: Prisma.EnumGradeEnumFilter<"Interview"> | $Enums.GradeEnum
  difficulty?: Prisma.EnumDifficultyEnumFilter<"Interview"> | $Enums.DifficultyEnum
  status?: Prisma.EnumStatusEnumFilter<"Interview"> | $Enums.StatusEnum
  hp?: Prisma.IntFilter<"Interview"> | number
  feedback?: Prisma.JsonNullableFilter<"Interview">
  createdAt?: Prisma.DateTimeFilter<"Interview"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Interview"> | Date | string
}

export type InterviewCreateManyUserInput = {
  id?: string
  topic: string
  grade: $Enums.GradeEnum
  difficulty: $Enums.DifficultyEnum
  status?: $Enums.StatusEnum
  hp?: number
  feedback?:PrismaJson.IInterviewFeedback | Prisma.NullableJsonNullValueInput
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type InterviewUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.EnumGradeEnumFieldUpdateOperationsInput | $Enums.GradeEnum
  difficulty?: Prisma.EnumDifficultyEnumFieldUpdateOperationsInput | $Enums.DifficultyEnum
  status?: Prisma.EnumStatusEnumFieldUpdateOperationsInput | $Enums.StatusEnum
  hp?: Prisma.IntFieldUpdateOperationsInput | number
  feedback?:PrismaJson.IInterviewFeedback | Prisma.NullableJsonNullValueInput
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  messages?: Prisma.MessageUpdateManyWithoutInterviewNestedInput
}

export type InterviewUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.EnumGradeEnumFieldUpdateOperationsInput | $Enums.GradeEnum
  difficulty?: Prisma.EnumDifficultyEnumFieldUpdateOperationsInput | $Enums.DifficultyEnum
  status?: Prisma.EnumStatusEnumFieldUpdateOperationsInput | $Enums.StatusEnum
  hp?: Prisma.IntFieldUpdateOperationsInput | number
  feedback?:PrismaJson.IInterviewFeedback | Prisma.NullableJsonNullValueInput
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  messages?: Prisma.MessageUncheckedUpdateManyWithoutInterviewNestedInput
}

export type InterviewUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.EnumGradeEnumFieldUpdateOperationsInput | $Enums.GradeEnum
  difficulty?: Prisma.EnumDifficultyEnumFieldUpdateOperationsInput | $Enums.DifficultyEnum
  status?: Prisma.EnumStatusEnumFieldUpdateOperationsInput | $Enums.StatusEnum
  hp?: Prisma.IntFieldUpdateOperationsInput | number
  feedback?:PrismaJson.IInterviewFeedback | Prisma.NullableJsonNullValueInput
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type InterviewCountOutputType
 */

export type InterviewCountOutputType = {
  messages: number
}

export type InterviewCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  messages?: boolean | InterviewCountOutputTypeCountMessagesArgs
}

/**
 * InterviewCountOutputType without action
 */
export type InterviewCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InterviewCountOutputType
   */
  select?: Prisma.InterviewCountOutputTypeSelect<ExtArgs> | null
}

/**
 * InterviewCountOutputType without action
 */
export type InterviewCountOutputTypeCountMessagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MessageWhereInput
}


export type InterviewSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  topic?: boolean
  grade?: boolean
  difficulty?: boolean
  status?: boolean
  hp?: boolean
  feedback?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  messages?: boolean | Prisma.Interview$messagesArgs<ExtArgs>
  _count?: boolean | Prisma.InterviewCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["interview"]>

export type InterviewSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  topic?: boolean
  grade?: boolean
  difficulty?: boolean
  status?: boolean
  hp?: boolean
  feedback?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["interview"]>

export type InterviewSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  topic?: boolean
  grade?: boolean
  difficulty?: boolean
  status?: boolean
  hp?: boolean
  feedback?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["interview"]>

export type InterviewSelectScalar = {
  id?: boolean
  userId?: boolean
  topic?: boolean
  grade?: boolean
  difficulty?: boolean
  status?: boolean
  hp?: boolean
  feedback?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type InterviewOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "topic" | "grade" | "difficulty" | "status" | "hp" | "feedback" | "createdAt" | "updatedAt", ExtArgs["result"]["interview"]>
export type InterviewInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  messages?: boolean | Prisma.Interview$messagesArgs<ExtArgs>
  _count?: boolean | Prisma.InterviewCountOutputTypeDefaultArgs<ExtArgs>
}
export type InterviewIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type InterviewIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $InterviewPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Interview"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    messages: Prisma.$MessagePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    topic: string
    grade: $Enums.GradeEnum
    difficulty: $Enums.DifficultyEnum
    status: $Enums.StatusEnum
    hp: number
    /**
     * [IInterviewFeedback]
     */
    feedback:PrismaJson.IInterviewFeedback | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["interview"]>
  composites: {}
}

export type InterviewGetPayload<S extends boolean | null | undefined | InterviewDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$InterviewPayload, S>

export type InterviewCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<InterviewFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: InterviewCountAggregateInputType | true
  }

export interface InterviewDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Interview'], meta: { name: 'Interview' } }
  /**
   * Find zero or one Interview that matches the filter.
   * @param {InterviewFindUniqueArgs} args - Arguments to find a Interview
   * @example
   * // Get one Interview
   * const interview = await prisma.interview.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends InterviewFindUniqueArgs>(args: Prisma.SelectSubset<T, InterviewFindUniqueArgs<ExtArgs>>): Prisma.Prisma__InterviewClient<runtime.Types.Result.GetResult<Prisma.$InterviewPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Interview that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {InterviewFindUniqueOrThrowArgs} args - Arguments to find a Interview
   * @example
   * // Get one Interview
   * const interview = await prisma.interview.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends InterviewFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, InterviewFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__InterviewClient<runtime.Types.Result.GetResult<Prisma.$InterviewPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Interview that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InterviewFindFirstArgs} args - Arguments to find a Interview
   * @example
   * // Get one Interview
   * const interview = await prisma.interview.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends InterviewFindFirstArgs>(args?: Prisma.SelectSubset<T, InterviewFindFirstArgs<ExtArgs>>): Prisma.Prisma__InterviewClient<runtime.Types.Result.GetResult<Prisma.$InterviewPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Interview that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InterviewFindFirstOrThrowArgs} args - Arguments to find a Interview
   * @example
   * // Get one Interview
   * const interview = await prisma.interview.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends InterviewFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, InterviewFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__InterviewClient<runtime.Types.Result.GetResult<Prisma.$InterviewPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Interviews that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InterviewFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Interviews
   * const interviews = await prisma.interview.findMany()
   * 
   * // Get first 10 Interviews
   * const interviews = await prisma.interview.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const interviewWithIdOnly = await prisma.interview.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends InterviewFindManyArgs>(args?: Prisma.SelectSubset<T, InterviewFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InterviewPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Interview.
   * @param {InterviewCreateArgs} args - Arguments to create a Interview.
   * @example
   * // Create one Interview
   * const Interview = await prisma.interview.create({
   *   data: {
   *     // ... data to create a Interview
   *   }
   * })
   * 
   */
  create<T extends InterviewCreateArgs>(args: Prisma.SelectSubset<T, InterviewCreateArgs<ExtArgs>>): Prisma.Prisma__InterviewClient<runtime.Types.Result.GetResult<Prisma.$InterviewPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Interviews.
   * @param {InterviewCreateManyArgs} args - Arguments to create many Interviews.
   * @example
   * // Create many Interviews
   * const interview = await prisma.interview.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends InterviewCreateManyArgs>(args?: Prisma.SelectSubset<T, InterviewCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Interviews and returns the data saved in the database.
   * @param {InterviewCreateManyAndReturnArgs} args - Arguments to create many Interviews.
   * @example
   * // Create many Interviews
   * const interview = await prisma.interview.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Interviews and only return the `id`
   * const interviewWithIdOnly = await prisma.interview.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends InterviewCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, InterviewCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InterviewPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Interview.
   * @param {InterviewDeleteArgs} args - Arguments to delete one Interview.
   * @example
   * // Delete one Interview
   * const Interview = await prisma.interview.delete({
   *   where: {
   *     // ... filter to delete one Interview
   *   }
   * })
   * 
   */
  delete<T extends InterviewDeleteArgs>(args: Prisma.SelectSubset<T, InterviewDeleteArgs<ExtArgs>>): Prisma.Prisma__InterviewClient<runtime.Types.Result.GetResult<Prisma.$InterviewPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Interview.
   * @param {InterviewUpdateArgs} args - Arguments to update one Interview.
   * @example
   * // Update one Interview
   * const interview = await prisma.interview.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends InterviewUpdateArgs>(args: Prisma.SelectSubset<T, InterviewUpdateArgs<ExtArgs>>): Prisma.Prisma__InterviewClient<runtime.Types.Result.GetResult<Prisma.$InterviewPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Interviews.
   * @param {InterviewDeleteManyArgs} args - Arguments to filter Interviews to delete.
   * @example
   * // Delete a few Interviews
   * const { count } = await prisma.interview.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends InterviewDeleteManyArgs>(args?: Prisma.SelectSubset<T, InterviewDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Interviews.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InterviewUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Interviews
   * const interview = await prisma.interview.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends InterviewUpdateManyArgs>(args: Prisma.SelectSubset<T, InterviewUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Interviews and returns the data updated in the database.
   * @param {InterviewUpdateManyAndReturnArgs} args - Arguments to update many Interviews.
   * @example
   * // Update many Interviews
   * const interview = await prisma.interview.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Interviews and only return the `id`
   * const interviewWithIdOnly = await prisma.interview.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends InterviewUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, InterviewUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InterviewPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Interview.
   * @param {InterviewUpsertArgs} args - Arguments to update or create a Interview.
   * @example
   * // Update or create a Interview
   * const interview = await prisma.interview.upsert({
   *   create: {
   *     // ... data to create a Interview
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Interview we want to update
   *   }
   * })
   */
  upsert<T extends InterviewUpsertArgs>(args: Prisma.SelectSubset<T, InterviewUpsertArgs<ExtArgs>>): Prisma.Prisma__InterviewClient<runtime.Types.Result.GetResult<Prisma.$InterviewPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Interviews.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InterviewCountArgs} args - Arguments to filter Interviews to count.
   * @example
   * // Count the number of Interviews
   * const count = await prisma.interview.count({
   *   where: {
   *     // ... the filter for the Interviews we want to count
   *   }
   * })
  **/
  count<T extends InterviewCountArgs>(
    args?: Prisma.Subset<T, InterviewCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], InterviewCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Interview.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InterviewAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends InterviewAggregateArgs>(args: Prisma.Subset<T, InterviewAggregateArgs>): Prisma.PrismaPromise<GetInterviewAggregateType<T>>

  /**
   * Group by Interview.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InterviewGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends InterviewGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: InterviewGroupByArgs['orderBy'] }
      : { orderBy?: InterviewGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, InterviewGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetInterviewGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Interview model
 */
readonly fields: InterviewFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Interview.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__InterviewClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  messages<T extends Prisma.Interview$messagesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Interview$messagesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Interview model
 */
export interface InterviewFieldRefs {
  readonly id: Prisma.FieldRef<"Interview", 'String'>
  readonly userId: Prisma.FieldRef<"Interview", 'String'>
  readonly topic: Prisma.FieldRef<"Interview", 'String'>
  readonly grade: Prisma.FieldRef<"Interview", 'GradeEnum'>
  readonly difficulty: Prisma.FieldRef<"Interview", 'DifficultyEnum'>
  readonly status: Prisma.FieldRef<"Interview", 'StatusEnum'>
  readonly hp: Prisma.FieldRef<"Interview", 'Int'>
  readonly feedback: Prisma.FieldRef<"Interview", 'Json'>
  readonly createdAt: Prisma.FieldRef<"Interview", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Interview", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Interview findUnique
 */
export type InterviewFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Interview
   */
  select?: Prisma.InterviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Interview
   */
  omit?: Prisma.InterviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InterviewInclude<ExtArgs> | null
  /**
   * Filter, which Interview to fetch.
   */
  where: Prisma.InterviewWhereUniqueInput
}

/**
 * Interview findUniqueOrThrow
 */
export type InterviewFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Interview
   */
  select?: Prisma.InterviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Interview
   */
  omit?: Prisma.InterviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InterviewInclude<ExtArgs> | null
  /**
   * Filter, which Interview to fetch.
   */
  where: Prisma.InterviewWhereUniqueInput
}

/**
 * Interview findFirst
 */
export type InterviewFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Interview
   */
  select?: Prisma.InterviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Interview
   */
  omit?: Prisma.InterviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InterviewInclude<ExtArgs> | null
  /**
   * Filter, which Interview to fetch.
   */
  where?: Prisma.InterviewWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Interviews to fetch.
   */
  orderBy?: Prisma.InterviewOrderByWithRelationInput | Prisma.InterviewOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Interviews.
   */
  cursor?: Prisma.InterviewWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Interviews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Interviews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Interviews.
   */
  distinct?: Prisma.InterviewScalarFieldEnum | Prisma.InterviewScalarFieldEnum[]
}

/**
 * Interview findFirstOrThrow
 */
export type InterviewFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Interview
   */
  select?: Prisma.InterviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Interview
   */
  omit?: Prisma.InterviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InterviewInclude<ExtArgs> | null
  /**
   * Filter, which Interview to fetch.
   */
  where?: Prisma.InterviewWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Interviews to fetch.
   */
  orderBy?: Prisma.InterviewOrderByWithRelationInput | Prisma.InterviewOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Interviews.
   */
  cursor?: Prisma.InterviewWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Interviews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Interviews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Interviews.
   */
  distinct?: Prisma.InterviewScalarFieldEnum | Prisma.InterviewScalarFieldEnum[]
}

/**
 * Interview findMany
 */
export type InterviewFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Interview
   */
  select?: Prisma.InterviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Interview
   */
  omit?: Prisma.InterviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InterviewInclude<ExtArgs> | null
  /**
   * Filter, which Interviews to fetch.
   */
  where?: Prisma.InterviewWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Interviews to fetch.
   */
  orderBy?: Prisma.InterviewOrderByWithRelationInput | Prisma.InterviewOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Interviews.
   */
  cursor?: Prisma.InterviewWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Interviews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Interviews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Interviews.
   */
  distinct?: Prisma.InterviewScalarFieldEnum | Prisma.InterviewScalarFieldEnum[]
}

/**
 * Interview create
 */
export type InterviewCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Interview
   */
  select?: Prisma.InterviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Interview
   */
  omit?: Prisma.InterviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InterviewInclude<ExtArgs> | null
  /**
   * The data needed to create a Interview.
   */
  data: Prisma.XOR<Prisma.InterviewCreateInput, Prisma.InterviewUncheckedCreateInput>
}

/**
 * Interview createMany
 */
export type InterviewCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Interviews.
   */
  data: Prisma.InterviewCreateManyInput | Prisma.InterviewCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Interview createManyAndReturn
 */
export type InterviewCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Interview
   */
  select?: Prisma.InterviewSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Interview
   */
  omit?: Prisma.InterviewOmit<ExtArgs> | null
  /**
   * The data used to create many Interviews.
   */
  data: Prisma.InterviewCreateManyInput | Prisma.InterviewCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InterviewIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Interview update
 */
export type InterviewUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Interview
   */
  select?: Prisma.InterviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Interview
   */
  omit?: Prisma.InterviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InterviewInclude<ExtArgs> | null
  /**
   * The data needed to update a Interview.
   */
  data: Prisma.XOR<Prisma.InterviewUpdateInput, Prisma.InterviewUncheckedUpdateInput>
  /**
   * Choose, which Interview to update.
   */
  where: Prisma.InterviewWhereUniqueInput
}

/**
 * Interview updateMany
 */
export type InterviewUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Interviews.
   */
  data: Prisma.XOR<Prisma.InterviewUpdateManyMutationInput, Prisma.InterviewUncheckedUpdateManyInput>
  /**
   * Filter which Interviews to update
   */
  where?: Prisma.InterviewWhereInput
  /**
   * Limit how many Interviews to update.
   */
  limit?: number
}

/**
 * Interview updateManyAndReturn
 */
export type InterviewUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Interview
   */
  select?: Prisma.InterviewSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Interview
   */
  omit?: Prisma.InterviewOmit<ExtArgs> | null
  /**
   * The data used to update Interviews.
   */
  data: Prisma.XOR<Prisma.InterviewUpdateManyMutationInput, Prisma.InterviewUncheckedUpdateManyInput>
  /**
   * Filter which Interviews to update
   */
  where?: Prisma.InterviewWhereInput
  /**
   * Limit how many Interviews to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InterviewIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Interview upsert
 */
export type InterviewUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Interview
   */
  select?: Prisma.InterviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Interview
   */
  omit?: Prisma.InterviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InterviewInclude<ExtArgs> | null
  /**
   * The filter to search for the Interview to update in case it exists.
   */
  where: Prisma.InterviewWhereUniqueInput
  /**
   * In case the Interview found by the `where` argument doesn't exist, create a new Interview with this data.
   */
  create: Prisma.XOR<Prisma.InterviewCreateInput, Prisma.InterviewUncheckedCreateInput>
  /**
   * In case the Interview was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.InterviewUpdateInput, Prisma.InterviewUncheckedUpdateInput>
}

/**
 * Interview delete
 */
export type InterviewDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Interview
   */
  select?: Prisma.InterviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Interview
   */
  omit?: Prisma.InterviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InterviewInclude<ExtArgs> | null
  /**
   * Filter which Interview to delete.
   */
  where: Prisma.InterviewWhereUniqueInput
}

/**
 * Interview deleteMany
 */
export type InterviewDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Interviews to delete
   */
  where?: Prisma.InterviewWhereInput
  /**
   * Limit how many Interviews to delete.
   */
  limit?: number
}

/**
 * Interview.messages
 */
export type Interview$messagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageInclude<ExtArgs> | null
  where?: Prisma.MessageWhereInput
  orderBy?: Prisma.MessageOrderByWithRelationInput | Prisma.MessageOrderByWithRelationInput[]
  cursor?: Prisma.MessageWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MessageScalarFieldEnum | Prisma.MessageScalarFieldEnum[]
}

/**
 * Interview without action
 */
export type InterviewDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Interview
   */
  select?: Prisma.InterviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Interview
   */
  omit?: Prisma.InterviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InterviewInclude<ExtArgs> | null
}
